version: '3.7'
services:
  mongo_db:
    image: mongo:latest
    container_name: mongoDB
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data_container:/data/db
  redis:
    container_name: redis
    hostname: redis
    image: redis
    ports:
      - "6379:6379"
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
volumes:
  mongodb_data_container: